=== Reino-Doce/dota-knowledge/schema/abilities.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/devilesk/dota-interactive-map/dota-knowledge/abilities.schema.json",
  "type": "object",
  "required": [
    "innate",
    "skills",
    "talents",
    "bonus_attributes"
  ],
  "properties": {
    "innate": {
      "oneOf": [
        {
          "type": "null"
        },
        {
          "$ref": "#/$defs/entry"
        },
        {
          "type": "array",
          "minItems": 2,
          "items": {
            "$ref": "#/$defs/entry"
          }
        }
      ]
    },
    "skills": {
      "type": "array",
      "items": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/$defs/entry"
          }
        ],
        "required": [
          "type"
        ]
      }
    },
    "talents": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/bonus"
      }
    },
    "bonus_attributes": {
      "oneOf": [
        {
          "type": "null"
        },
        {
          "$ref": "#/$defs/bonus"
        },
        {
          "type": "array",
          "minItems": 2,
          "items": {
            "$ref": "#/$defs/bonus"
          }
        }
      ]
    }
  },
  "additionalProperties": false,
  "$defs": {
    "quantity": {
      "oneOf": [
        {
          "type": "number",
          "minimum": 0
        },
        {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "number",
            "minimum": 0
          }
        }
      ]
    },
    "entry": {
      "type": "object",
      "required": [
        "id",
        "tags"
      ],
      "properties": {
        "id": {
          "type": "string",
          "minLength": 1
        },
        "type": {
          "enum": [
            "passive",
            "toggle",
            "target",
            "point",
            "vector",
            "target-or-point",
            "self-target",
            "unknown",
            "placeholder"
          ]
        },
        "behavior": {
          "type": "array",
          "minItems": 1,
          "uniqueItems": true,
          "items": {
            "enum": [
              "unit-target",
              "passive",
              "point-target",
              "no-target",
              "auto-cast",
              "channeled",
              "point-vector-target",
              "toggle",
              "tree-vector-target"
            ]
          }
        },
        "affects": {
          "type": "array",
          "minItems": 1,
          "uniqueItems": true,
          "items": {
            "enum": [
              "units",
              "allies",
              "allied-units",
              "enemy-units",
              "enemy-creeps",
              "allied-heroes",
              "enemy-heroes",
              "trees",
              "allied-buildings",
              "enemy-buildings"
            ]
          }
        },
        "dispellable": {
          "enum": [
            "yes",
            "no",
            "strong-only"
          ]
        },
        "dispelType": {
          "enum": [
            "basic",
            "strong"
          ]
        },
        "piercesDebuffImmunity": {
          "enum": [
            "no",
            "allies-only",
            "yes"
          ]
        },
        "damageType": {
          "enum": [
            "physical",
            "magical",
            "pure"
          ]
        },
        "breakable": {
          "type": "boolean"
        },
        "target": {
          "type": "array",
          "minItems": 1,
          "uniqueItems": true,
          "items": {
            "enum": [
              "self",
              "ally_hero",
              "enemy_hero",
              "ally_creep",
              "enemy_creep",
              "neutral_creep",
              "enemy_creep_hero",
              "ally_building",
              "enemy_building",
              "tree",
              "ally_courier",
              "enemy_courier"
            ]
          }
        },
        "manaCost": {
          "$ref": "#/$defs/quantity"
        },
        "cooldown": {
          "$ref": "#/$defs/quantity"
        },
        "tags": {
          "type": "array",
          "items": {
            "type": "string",
            "pattern": "^[a-z][a-z0-9_]{0,63}$"
          },
          "uniqueItems": true
        },
        "order": {
          "type": "integer",
          "minimum": 0
        },
        "Name": {
          "type": "string",
          "minLength": 1
        }
      },
      "additionalProperties": false
    },
    "bonus": {
      "type": "object",
      "required": [
        "id",
        "tags"
      ],
      "properties": {
        "id": {
          "type": "string",
          "minLength": 1
        },
        "behavior": {
          "type": "array",
          "minItems": 1,
          "uniqueItems": true,
          "items": {
            "enum": [
              "unit-target",
              "passive",
              "point-target",
              "no-target",
              "auto-cast",
              "channeled",
              "point-vector-target",
              "toggle",
              "tree-vector-target"
            ]
          }
        },
        "affects": {
          "type": "array",
          "minItems": 1,
          "uniqueItems": true,
          "items": {
            "enum": [
              "units",
              "allies",
              "allied-units",
              "enemy-units",
              "enemy-creeps",
              "allied-heroes",
              "enemy-heroes",
              "trees",
              "allied-buildings",
              "enemy-buildings"
            ]
          }
        },
        "dispellable": {
          "enum": [
            "yes",
            "no",
            "strong-only"
          ]
        },
        "dispelType": {
          "enum": [
            "basic",
            "strong"
          ]
        },
        "piercesDebuffImmunity": {
          "enum": [
            "no",
            "allies-only",
            "yes"
          ]
        },
        "damageType": {
          "enum": [
            "physical",
            "magical",
            "pure"
          ]
        },
        "breakable": {
          "type": "boolean"
        },
        "tags": {
          "type": "array",
          "items": {
            "type": "string",
            "pattern": "^[a-z][a-z0-9_]{0,63}$"
          },
          "uniqueItems": true
        },
        "Name": {
          "type": "string",
          "minLength": 1
        }
      },
      "additionalProperties": false
    },
    "legacy": {
      "type": "object",
      "required": [
        "schemaVersion",
        "abilities",
        "activations"
      ],
      "properties": {
        "schemaVersion": {
          "const": 2
        },
        "abilities": {
          "type": "array",
          "items": {
            "$ref": "core.schema.json#/$defs/ability"
          }
        },
        "activations": {
          "type": "array",
          "items": {
            "$ref": "core.schema.json#/$defs/activation"
          }
        }
      },
      "additionalProperties": false
    }
  }
}

=== Reino-Doce/dota-knowledge/data/heroes/marci/abilities.json
{
  "innate": {
    "id": "marci_special_delivery",
    "Name": "Special Delivery",
    "behavior": [
      "no-target"
    ],
    "type": "self-target",
    "tags": [
      "courier_utility"
    ]
  },
  "skills": [
    {
      "id": "marci_grapple",
      "Name": "Dispose",
      "behavior": [
        "unit-target"
      ],
      "affects": [
        "units"
      ],
      "dispellable": "yes",
      "dispelType": "basic",
      "piercesDebuffImmunity": "no",
      "damageType": "magical",
      "order": 0,
      "type": "target",
      "target": [
        "self",
        "ally_hero",
        "enemy_hero",
        "ally_creep",
        "enemy_creep",
        "neutral_creep"
      ],
      "manaCost": 80,
      "cooldown": [
        16,
        14,
        12,
        10
      ],
      "tags": [
        "ally_reposition",
        "enemy_displacement",
        "escape",
        "mobility",
        "slow"
      ]
    },
    {
      "id": "marci_companion_run",
      "Name": "Rebound",
      "behavior": [
        "point-vector-target",
        "unit-target"
      ],
      "affects": [
        "allied-units"
      ],
      "dispellable": "strong-only",
      "dispelType": "strong",
      "piercesDebuffImmunity": "no",
      "damageType": "magical",
      "order": 1,
      "type": "vector",
      "target": [
        "self",
        "ally_hero"
      ],
      "manaCost": [
        70,
        80,
        90,
        100
      ],
      "tags": [
        "ally_movement_speed",
        "buff",
        "disable",
        "escape",
        "mobility",
        "stun"
      ]
    },
    {
      "id": "marci_bodyguard",
      "Name": "Bodyguard",
      "behavior": [
        "unit-target"
      ],
      "affects": [
        "allied-heroes"
      ],
      "dispellable": "yes",
      "dispelType": "basic",
      "piercesDebuffImmunity": "allies-only",
      "damageType": "physical",
      "order": 2,
      "type": "target",
      "target": [
        "self",
        "ally_hero"
      ],
      "manaCost": 60,
      "cooldown": 20,
      "tags": [
        "barrier",
        "buff",
        "damage_sharing",
        "lifesteal",
        "self_attack_damage",
        "self_lifesteal"
      ]
    },
    {
      "id": "generic_hidden",
      "order": 4,
      "type": "unknown",
      "tags": []
    },
    {
      "id": "marci_unleash",
      "Name": "Unleash",
      "behavior": [
        "no-target"
      ],
      "dispellable": "no",
      "damageType": "magical",
      "order": 5,
      "type": "self-target",
      "tags": [
        "buff",
        "damage_over_time",
        "dispel",
        "enemy_attack_speed_reduction",
        "self_attack_speed",
        "self_movement_speed",
        "slow"
      ]
    },
    {
      "id": "marci_guardian",
      "behavior": [
        "unit-target"
      ],
      "affects": [
        "allied-heroes"
      ],
      "dispellable": "no",
      "piercesDebuffImmunity": "allies-only",
      "damageType": "physical",
      "order": 15,
      "type": "target",
      "target": [
        "self",
        "ally_hero"
      ],
      "manaCost": [
        45,
        40,
        35,
        30
      ],
      "cooldown": 20,
      "tags": [
        "ally_attack_damage",
        "buff",
        "lifesteal",
        "self_attack_damage",
        "self_lifesteal"
      ]
    }
  ],
  "talents": [
    {
      "id": "special_bonus_unique_marci_dispose_slow",
      "behavior": [
        "passive"
      ],
      "tags": []
    },
    {
      "id": "special_bonus_unique_marci_rebound_radius",
      "behavior": [
        "passive"
      ],
      "tags": []
    },
    {
      "id": "special_bonus_unique_marci_grapple_damage",
      "behavior": [
        "passive"
      ],
      "tags": [
        "ability_damage_bonus",
        "buff"
      ]
    },
    {
      "id": "special_bonus_unique_marci_guardian_damage",
      "behavior": [
        "passive"
      ],
      "tags": [
        "ally_attack_damage",
        "buff",
        "self_attack_damage"
      ]
    },
    {
      "id": "special_bonus_unique_marci_grapple_stun_duration",
      "behavior": [
        "passive"
      ],
      "tags": []
    },
    {
      "id": "special_bonus_unique_marci_unleash_speed",
      "behavior": [
        "passive"
      ],
      "tags": []
    },
    {
      "id": "special_bonus_unique_marci_unleash_extend_duration",
      "behavior": [
        "passive"
      ],
      "tags": []
    },
    {
      "id": "special_bonus_unique_marci_guardian_strong_dispel",
      "Name": "Bodyguard Strong Dispels",
      "tags": []
    },
    {
      "id": "special_bonus_unique_marci_guardian_lifesteal",
      "behavior": [
        "passive"
      ],
      "tags": []
    },
    {
      "id": "special_bonus_unique_marci_lunge_range",
      "behavior": [
        "passive"
      ],
      "tags": [
        "buff",
        "cast_range"
      ]
    },
    {
      "id": "special_bonus_unique_marci_lunge_movespeed",
      "behavior": [
        "passive"
      ],
      "tags": []
    }
  ],
  "bonus_attributes": {
    "id": "special_bonus_attributes",
    "behavior": [
      "passive"
    ],
    "tags": []
  }
}

=== Reino-Doce/dota-knowledge/data/heroes/shadow_demon/abilities.json
{
  "innate": [
    {
      "id": "shadow_demon_menace",
      "Name": "Menace",
      "behavior": [
        "passive"
      ],
      "dispellable": "no",
      "breakable": true,
      "tags": [
        "incoming_damage_amplification"
      ]
    },
    {
      "id": "shadow_demon_shadow_servant",
      "Name": "Soul Catcher",
      "behavior": [
        "passive"
      ],
      "tags": [
        "illusions"
      ]
    }
  ],
  "skills": [
    {
      "id": "shadow_demon_disruption",
      "Name": "Disruption",
      "behavior": [
        "unit-target"
      ],
      "affects": [
        "allied-heroes",
        "enemy-heroes"
      ],
      "dispellable": "no",
      "piercesDebuffImmunity": "no",
      "order": 0,
      "type": "target",
      "target": [
        "self",
        "ally_hero",
        "enemy_hero"
      ],
      "manaCost": 120,
      "tags": [
        "illusions"
      ]
    },
    {
      "id": "shadow_demon_disseminate",
      "Name": "Disseminate",
      "behavior": [
        "unit-target"
      ],
      "affects": [
        "units"
      ],
      "piercesDebuffImmunity": "no",
      "order": 1,
      "type": "target",
      "target": [
        "self",
        "ally_hero",
        "enemy_hero",
        "ally_creep",
        "enemy_creep",
        "neutral_creep"
      ],
      "manaCost": 100,
      "cooldown": [
        26,
        22,
        18,
        14
      ],
      "tags": [
        "aoe",
        "buff",
        "cast_range"
      ]
    },
    {
      "id": "shadow_demon_shadow_poison",
      "Name": "Shadow Poison",
      "behavior": [
        "point-target"
      ],
      "dispellable": "no",
      "piercesDebuffImmunity": "no",
      "damageType": "magical",
      "order": 2,
      "type": "point",
      "manaCost": 40,
      "tags": [
        "aoe"
      ]
    },
    {
      "id": "shadow_demon_shadow_poison_release",
      "Name": "Shadow Poison Release",
      "behavior": [
        "no-target"
      ],
      "order": 3,
      "type": "self-target",
      "cooldown": 1,
      "tags": []
    },
    {
      "id": "shadow_demon_demonic_cleanse",
      "Name": "Demonic Cleanse",
      "behavior": [
        "unit-target"
      ],
      "affects": [
        "allied-units"
      ],
      "dispellable": "no",
      "piercesDebuffImmunity": "yes",
      "order": 4,
      "type": "target",
      "target": [
        "self",
        "ally_hero",
        "ally_creep"
      ],
      "manaCost": 150,
      "cooldown": 60,
      "tags": [
        "ally_dispel",
        "dispel"
      ]
    },
    {
      "id": "shadow_demon_demonic_purge",
      "Name": "Demonic Purge",
      "behavior": [
        "unit-target"
      ],
      "affects": [
        "enemy-units"
      ],
      "dispellable": "no",
      "piercesDebuffImmunity": "yes",
      "damageType": "magical",
      "order": 5,
      "type": "target",
      "target": [
        "enemy_hero",
        "enemy_creep",
        "neutral_creep"
      ],
      "manaCost": [
        150,
        175,
        200
      ],
      "tags": [
        "bkb_pierce",
        "break",
        "dispel",
        "slow"
      ]
    },
    {
      "id": "shadow_demon_soul_catcher",
      "behavior": [
        "point-target"
      ],
      "dispellable": "yes",
      "dispelType": "basic",
      "piercesDebuffImmunity": "no",
      "damageType": "pure",
      "order": 16,
      "type": "point",
      "manaCost": [
        80,
        100,
        120,
        140
      ],
      "cooldown": [
        26,
        24,
        22,
        20
      ],
      "tags": [
        "aoe"
      ]
    }
  ],
  "talents": [
    {
      "id": "special_bonus_unique_shadow_demon_4",
      "tags": []
    },
    {
      "id": "special_bonus_strength_8",
      "Name": "+8 Strength",
      "behavior": [
        "passive"
      ],
      "tags": [
        "attribute_bonus",
        "buff"
      ]
    },
    {
      "id": "special_bonus_movement_speed_20",
      "Name": "+20 Movement Speed",
      "behavior": [
        "passive"
      ],
      "tags": [
        "buff",
        "self_movement_speed"
      ]
    },
    {
      "id": "special_bonus_unique_shadow_demon_3",
      "tags": [
        "buff",
        "cooldown_reduction"
      ]
    },
    {
      "id": "special_bonus_unique_shadow_demon_disseminate_damage",
      "tags": []
    },
    {
      "id": "special_bonus_unique_shadow_demon_9",
      "tags": [
        "buff",
        "cooldown_reduction"
      ]
    },
    {
      "id": "special_bonus_unique_shadow_demon_purge_poison",
      "Name": "Demonic Purge Applies Shadow Poison",
      "tags": []
    },
    {
      "id": "special_bonus_unique_shadow_demon_7",
      "tags": [
        "buff",
        "cooldown_reduction"
      ]
    }
  ],
  "bonus_attributes": {
    "id": "special_bonus_attributes",
    "behavior": [
      "passive"
    ],
    "tags": []
  }
}

=== Reino-Doce/dota-knowledge/data/heroes/enigma/abilities.json
{
  "innate": [
    {
      "id": "enigma_event_horizon",
      "Name": "Event Horizon",
      "behavior": [
        "passive"
      ],
      "dispellable": "no",
      "breakable": true,
      "tags": [
        "slow"
      ]
    },
    {
      "id": "enigma_gravity_well",
      "Name": "Gravity Well",
      "behavior": [
        "passive"
      ],
      "breakable": true,
      "tags": [
        "buff",
        "damage_reduction"
      ]
    }
  ],
  "skills": [
    {
      "id": "enigma_malefice",
      "Name": "Malefice",
      "behavior": [
        "unit-target"
      ],
      "affects": [
        "enemy-units"
      ],
      "dispellable": "yes",
      "dispelType": "basic",
      "piercesDebuffImmunity": "no",
      "damageType": "magical",
      "order": 0,
      "type": "target",
      "target": [
        "enemy_hero",
        "enemy_creep",
        "neutral_creep"
      ],
      "manaCost": [
        100,
        110,
        120,
        130
      ],
      "cooldown": [
        20,
        18,
        16,
        14
      ],
      "tags": [
        "damage_over_time",
        "disable",
        "stun"
      ]
    },
    {
      "id": "enigma_demonic_conversion",
      "Name": "Demonic Summoning",
      "behavior": [
        "point-target"
      ],
      "damageType": "physical",
      "order": 1,
      "type": "point",
      "manaCost": [
        70,
        80,
        90,
        100
      ],
      "cooldown": [
        45,
        40,
        35,
        30
      ],
      "tags": [
        "summons"
      ]
    },
    {
      "id": "enigma_midnight_pulse",
      "Name": "Midnight Pulse",
      "behavior": [
        "point-target"
      ],
      "piercesDebuffImmunity": "yes",
      "damageType": "magical",
      "order": 2,
      "type": "point",
      "manaCost": [
        65,
        90,
        115,
        140
      ],
      "cooldown": [
        40,
        35,
        30,
        25
      ],
      "tags": [
        "aoe",
        "bkb_pierce",
        "damage_over_time"
      ]
    },
    {
      "id": "generic_hidden",
      "order": 4,
      "type": "unknown",
      "tags": []
    },
    {
      "id": "enigma_black_hole",
      "Name": "Black Hole",
      "behavior": [
        "channeled",
        "point-target"
      ],
      "piercesDebuffImmunity": "yes",
      "damageType": "pure",
      "order": 5,
      "type": "point",
      "manaCost": [
        300,
        400,
        500
      ],
      "cooldown": [
        180,
        170,
        160
      ],
      "tags": [
        "aoe",
        "bkb_pierce",
        "channeled",
        "enemy_displacement"
      ]
    },
    {
      "id": "enigma_splitting_image",
      "Name": "Splitting Image",
      "behavior": [
        "passive"
      ],
      "dispellable": "no",
      "breakable": true,
      "order": 16,
      "type": "passive",
      "tags": [
        "summons"
      ]
    }
  ],
  "talents": [
    {
      "id": "special_bonus_unique_enigma_4",
      "behavior": [
        "passive"
      ],
      "tags": []
    },
    {
      "id": "special_bonus_unique_enigma_6",
      "behavior": [
        "passive"
      ],
      "tags": [
        "ability_damage_bonus",
        "buff"
      ]
    },
    {
      "id": "special_bonus_hp_250",
      "Name": "+250 Health",
      "behavior": [
        "passive"
      ],
      "tags": [
        "buff",
        "self_max_health"
      ]
    },
    {
      "id": "special_bonus_unique_enigma_5",
      "behavior": [
        "passive"
      ],
      "tags": []
    },
    {
      "id": "special_bonus_unique_enigma_9",
      "behavior": [
        "passive"
      ],
      "tags": [
        "area_increase",
        "buff"
      ]
    },
    {
      "id": "special_bonus_unique_enigma_3",
      "behavior": [
        "passive"
      ],
      "tags": []
    },
    {
      "id": "special_bonus_unique_enigma_2",
      "behavior": [
        "passive"
      ],
      "tags": []
    },
    {
      "id": "special_bonus_unique_enigma",
      "behavior": [
        "passive"
      ],
      "tags": []
    }
  ],
  "bonus_attributes": {
    "id": "special_bonus_attributes",
    "behavior": [
      "passive"
    ],
    "tags": []
  }
}

=== Reino-Doce/dota-knowledge/data/heroes/sven/abilities.json
{
  "innate": [
    {
      "id": "sven_wrath_of_god",
      "Name": "Wrath of God",
      "behavior": [
        "passive"
      ],
      "breakable": true,
      "tags": [
        "attribute_bonus",
        "buff",
        "self_attack_damage"
      ]
    },
    {
      "id": "sven_vanquisher",
      "Name": "Vanquisher",
      "behavior": [
        "passive"
      ],
      "breakable": true,
      "tags": [
        "buff",
        "self_attack_damage"
      ]
    }
  ],
  "skills": [
    {
      "id": "sven_storm_bolt",
      "Name": "Storm Hammer",
      "behavior": [
        "unit-target"
      ],
      "affects": [
        "enemy-units"
      ],
      "dispellable": "strong-only",
      "dispelType": "strong",
      "piercesDebuffImmunity": "no",
      "damageType": "magical",
      "order": 0,
      "type": "target",
      "target": [
        "enemy_hero",
        "enemy_creep",
        "neutral_creep"
      ],
      "tags": [
        "aoe",
        "disable",
        "dispel",
        "escape",
        "mobility",
        "self_reposition",
        "stun"
      ]
    },
    {
      "id": "sven_great_cleave",
      "Name": "Great Cleave",
      "behavior": [
        "passive"
      ],
      "piercesDebuffImmunity": "yes",
      "breakable": true,
      "order": 1,
      "type": "passive",
      "tags": [
        "attack_damage_scaling",
        "bkb_pierce",
        "cleave"
      ]
    },
    {
      "id": "sven_warcry",
      "Name": "Warcry",
      "behavior": [
        "no-target"
      ],
      "dispellable": "yes",
      "dispelType": "basic",
      "piercesDebuffImmunity": "allies-only",
      "breakable": true,
      "order": 2,
      "type": "self-target",
      "manaCost": [
        30,
        35,
        40,
        45
      ],
      "cooldown": [
        36,
        32,
        28,
        24
      ],
      "tags": [
        "ally_armor",
        "ally_movement_speed",
        "buff",
        "self_movement_speed"
      ]
    },
    {
      "id": "generic_hidden",
      "order": 3,
      "type": "unknown",
      "tags": []
    },
    {
      "id": "sven_gods_strength",
      "Name": "God's Strength",
      "behavior": [
        "no-target"
      ],
      "dispellable": "no",
      "order": 4,
      "type": "self-target",
      "manaCost": [
        100,
        125,
        150
      ],
      "tags": [
        "attack_damage_scaling",
        "buff",
        "slow_resistance"
      ]
    }
  ],
  "talents": [
    {
      "id": "special_bonus_unique_sven_5",
      "tags": [
        "duration_extension"
      ]
    },
    {
      "id": "special_bonus_unique_sven_gods_strength_slow_resist",
      "tags": []
    },
    {
      "id": "special_bonus_unique_sven_3",
      "tags": [
        "buff",
        "cooldown_reduction"
      ]
    },
    {
      "id": "special_bonus_unique_sven_8",
      "tags": []
    },
    {
      "id": "special_bonus_unique_sven_stormhammer_cooldown",
      "tags": [
        "buff",
        "cooldown_reduction",
        "mana_cost_reduction"
      ]
    },
    {
      "id": "special_bonus_unique_sven_7",
      "tags": [
        "ally_armor",
        "buff"
      ]
    },
    {
      "id": "special_bonus_unique_sven_2",
      "tags": []
    },
    {
      "id": "special_bonus_unique_sven_4",
      "tags": [
        "duration_extension",
        "stun"
      ]
    }
  ],
  "bonus_attributes": {
    "id": "special_bonus_attributes",
    "behavior": [
      "passive"
    ],
    "tags": []
  }
}
